### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Crystal-Gaming** [philxyz/darkrp2.2#1]
[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

[ERROR] lua/includes/modules/draw.lua:142: 'ScoreboardText' isn't a valid font
1. SetFont - [C]:-1
   1. DrawText - lua/includes/modules/draw.lua:142
   2. unknown - gamemodes/darkrp/gamemode/cl_init.lua:377

**Comment by philxyz** [comment]
I added the missing font. Please retest.
