### ISSUE TITLE
Next Error

### ISSUE THREAD

**Issue by Crystal-Gaming** [philxyz/darkrp2.2#2]
Here one more errors:
Thanks for fixxed Textures and more..

i send you ever errors :dancer: 

Here the Hunger Errors:
[DarkRP] gamemodes/darkrp/gamemode/modules/hungermod.lua:1: attempt to call global 'includeCS' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/hungermod.lua:1
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/init.lua:54

[DarkRP] gamemodes/darkrp/gamemode/modules/sleep.lua:56: attempt to call global 'AddChatCommand' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/sleep.lua:56
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/init.lua:54

**Comment by Crystal-Gaming** [comment]
[DarkRP] gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua:28: attempt to index global 'surface' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/hungermod/cl_init.lua:28
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/modules/hungermod.lua:1
      1. include - [C]:-1
      2. unknown - gamemodes/darkrp/gamemode/init.lua:54

Couldn't include file 'hungermod/player.lua' (File not found) (@gamemodes/darkrp/gamemode/modules/hungermod.lua (line 3))

[DarkRP] gamemodes/darkrp/gamemode/modules/hungermod.lua:10: attempt to index global 'CfgVars' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/hungermod.lua:10
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/init.lua:54

[DarkRP] gamemodes/darkrp/gamemode/modules/sleep.lua:56: attempt to call global 'AddChatCommand' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/sleep.lua:56
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/init.lua:54

**Comment by philxyz** [comment]
OK, please tell me if the new changes fixed these errors.

Thanks

**Comment by Crystal-Gaming** [comment]
Good Hunger is Fixxed and here the Sleep

[DarkRP] gamemodes/darkrp/gamemode/modules/sleep.lua:56: attempt to call global 'AddChatCommand' (a nil value)
1. unknown - gamemodes/darkrp/gamemode/modules/sleep.lua:56
   1. include - [C]:-1
   2. unknown - gamemodes/darkrp/gamemode/init.lua:54

**Comment by Crystal-Gaming** [comment]
is this concommand.add

**Comment by philxyz** [comment]
Fixed - please see the new INSTALL.txt file for installation details. Once you've got the latest files, replace your old ones, just in case.
